<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Predicting Happiness from Lifestyle and Mental Health Factors – Ngoc Nhu Y Nguyen</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Ngoc Nhu Y Nguyen</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Math437_Project.html" aria-current="page"> <i class="bi bi-megaphone" role="img">
</i> 
<span class="menu-text">Math 437 - Project</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#motivation-and-context" id="toc-motivation-and-context" class="nav-link active" data-scroll-target="#motivation-and-context">Motivation and Context</a>
  <ul class="collapse">
  <li><a href="#diet-types" id="toc-diet-types" class="nav-link" data-scroll-target="#diet-types">Diet Types</a></li>
  <li><a href="#mental-health-conditions" id="toc-mental-health-conditions" class="nav-link" data-scroll-target="#mental-health-conditions">Mental Health Conditions</a></li>
  </ul></li>
  <li><a href="#main-objective" id="toc-main-objective" class="nav-link" data-scroll-target="#main-objective">Main Objective</a></li>
  <li><a href="#packages-used-in-this-analysis" id="toc-packages-used-in-this-analysis" class="nav-link" data-scroll-target="#packages-used-in-this-analysis">Packages Used In This Analysis</a></li>
  <li><a href="#data-description" id="toc-data-description" class="nav-link" data-scroll-target="#data-description">Data Description</a>
  <ul class="collapse">
  <li><a href="#data-limitations" id="toc-data-limitations" class="nav-link" data-scroll-target="#data-limitations">Data Limitations</a></li>
  </ul></li>
  <li><a href="#data-wrangling-optional-section" id="toc-data-wrangling-optional-section" class="nav-link" data-scroll-target="#data-wrangling-optional-section">Data Wrangling (Optional Section)</a>
  <ul class="collapse">
  <li><a href="#handling-missing-data" id="toc-handling-missing-data" class="nav-link" data-scroll-target="#handling-missing-data">Handling Missing Data</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#happiness-score-response-variable" id="toc-happiness-score-response-variable" class="nav-link" data-scroll-target="#happiness-score-response-variable">1. Happiness Score (Response Variable)</a></li>
  <li><a href="#screen-time-per-day-hours" id="toc-screen-time-per-day-hours" class="nav-link" data-scroll-target="#screen-time-per-day-hours">2. Screen Time per Day (Hours)</a></li>
  <li><a href="#sleep-hours" id="toc-sleep-hours" class="nav-link" data-scroll-target="#sleep-hours">3. Sleep Hours</a></li>
  <li><a href="#relationship-between-lifestyle-and-happiness" id="toc-relationship-between-lifestyle-and-happiness" class="nav-link" data-scroll-target="#relationship-between-lifestyle-and-happiness">4. Relationship between Lifestyle and Happiness</a></li>
  </ul></li>
  <li><a href="#modeling" id="toc-modeling" class="nav-link" data-scroll-target="#modeling">Modeling</a></li>
  <li><a href="#insights" id="toc-insights" class="nav-link" data-scroll-target="#insights">Insights</a>
  <ul class="collapse">
  <li><a href="#limitations-and-future-work" id="toc-limitations-and-future-work" class="nav-link" data-scroll-target="#limitations-and-future-work">Limitations and Future Work</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting Happiness from Lifestyle and Mental Health Factors</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="motivation-and-context" class="level2">
<h2 class="anchored" data-anchor-id="motivation-and-context">Motivation and Context</h2>
<p>Mental health is one of the most important parts of a person’s overall well-being. One way to measure how people feel is by looking at their <strong>happiness</strong>—a key part of mental health. This project looks at how daily habits like diet, exercise, sleep, and screen time, as well as mental health conditions like anxiety or depression, might affect how happy people feel.</p>
<p>This topic matters to me because I believe small lifestyle changes can make a big difference in how we feel each day. If we can find out which habits or health conditions have the strongest connection to happiness, people can make better decisions for their own well-being. This research could also be useful for doctors, therapists, teachers, and public health leaders who want to help others feel happier and healthier.</p>
<p>To follow along with this analysis, it helps to understand a few key terms:</p>
<section id="diet-types" class="level3">
<h3 class="anchored" data-anchor-id="diet-types">Diet Types</h3>
<ul>
<li><strong>Vegetarian</strong>: Does not include meat but may include dairy or eggs.</li>
<li><strong>Vegan</strong>: Does not include any animal products, including dairy, eggs, or honey.</li>
<li><strong>Balanced diet</strong>: Includes a mix of healthy foods like fruits, vegetables, proteins, grains, and fats.</li>
<li><strong>Keto</strong>: A low-carb, high-fat diet that helps the body burn fat instead of sugar for energy.</li>
<li><strong>Junk food</strong>: Foods that are highly processed and full of sugar or unhealthy fats, like fast food and soda.</li>
</ul>
</section>
<section id="mental-health-conditions" class="level3">
<h3 class="anchored" data-anchor-id="mental-health-conditions">Mental Health Conditions</h3>
<ul>
<li><strong>PTSD</strong>: A condition that can happen after a scary or traumatic event, causing flashbacks or anxiety.</li>
<li><strong>Depression</strong>: A condition where a person feels very sad, hopeless, and loses interest in things they used to enjoy.</li>
<li><strong>Anxiety</strong>: Strong feelings of worry or fear that can get in the way of daily life.</li>
<li><strong>Bipolar disorder</strong>: A condition where a person’s mood swings between extreme highs (called mania) and deep lows (depression).</li>
</ul>
<p>Many scientists and health experts believe there is a strong connection between lifestyle, mental health, and happiness. For example, getting regular exercise can boost mood, while poor sleep or high stress can make people feel worse. This project will explore those connections and try to figure out which habits and conditions are most related to how happy someone feels.</p>
</section>
</section>
<section id="main-objective" class="level2">
<h2 class="anchored" data-anchor-id="main-objective">Main Objective</h2>
<p>The main goal of this project is to <strong>predict a person’s happiness score</strong> based on their lifestyle habits and mental health conditions.</p>
<p>By analyzing the “Mental Health and Lifestyle Habits Dataset (2019–2024),” I aim to identify which factors—such as diet, exercise, sleep, screen time, and existing mental health conditions—are most strongly associated with happiness. To do this, I will use a statistical modeling technique called <strong>LASSO regression</strong>, which not only builds a predictive model but also helps select the most important variables from the data.</p>
<p>Ultimately, the objective is to better understand how everyday choices and psychological well-being are linked to happiness, and to provide insights that could help individuals and professionals support mental health more effectively.</p>
</section>
<section id="packages-used-in-this-analysis" class="level2">
<h2 class="anchored" data-anchor-id="packages-used-in-this-analysis">Packages Used In This Analysis</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rsample)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(parsnip)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(recipes)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(workflows)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tune)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(yardstick)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dials)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(selectiveInference)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Package</th>
<th>Use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="https://github.com/jennybc/here_here">here</a></td>
<td>to easily load and save data</td>
</tr>
<tr class="even">
<td><a href="https://readr.tidyverse.org/">readr</a></td>
<td>to import the CSV file data</td>
</tr>
<tr class="odd">
<td><a href="https://dplyr.tidyverse.org/">dplyr</a></td>
<td>to massage and summarize data</td>
</tr>
<tr class="even">
<td><a href="https://rsample.tidymodels.org/">rsample</a></td>
<td>to split data into training and test sets</td>
</tr>
<tr class="odd">
<td><a href="https://ggplot2.tidyverse.org/">ggplot2</a></td>
<td>to create nice-looking and informative graphs</td>
</tr>
<tr class="even">
<td><a href="https://naniar.njtierney.com/">naniar</a></td>
<td>to summarize and visualize missing data</td>
</tr>
<tr class="odd">
<td><a href="https://parsnip.tidymodels.org/">parsnip</a></td>
<td>to define and fit models in a unified framework</td>
</tr>
<tr class="even">
<td><a href="https://recipes.tidymodels.org/">recipes</a></td>
<td>to preprocess data through feature engineering steps</td>
</tr>
<tr class="odd">
<td><a href="https://workflows.tidymodels.org/">workflows</a></td>
<td>to combine preprocessing and modeling into a single object</td>
</tr>
<tr class="even">
<td><a href="https://tune.tidymodels.org/">tune</a></td>
<td>to tune model hyperparameters through resampling</td>
</tr>
<tr class="odd">
<td><a href="https://yardstick.tidymodels.org/">yardstick</a></td>
<td>to evaluate and compare model performance</td>
</tr>
<tr class="even">
<td><a href="https://dials.tidymodels.org/">dials</a></td>
<td>to define and generate hyperparameter tuning grids</td>
</tr>
<tr class="odd">
<td><a href="https://glmnet.stanford.edu/">glmnet</a></td>
<td>to fit regularized linear models like LASSO and Ridge</td>
</tr>
<tr class="even">
<td><a href="https://cran.r-project.org/package=selectiveInference">selectiveInference</a></td>
<td>to compute post-selection inference for LASSO models</td>
</tr>
<tr class="odd">
<td><a href="https://broom.tidymodels.org/">broom</a></td>
<td>to convert model outputs into tidy tibbles</td>
</tr>
</tbody>
</table>
</section>
<section id="data-description" class="level2">
<h2 class="anchored" data-anchor-id="data-description">Data Description</h2>
<p>The dataset used in this project is titled <strong>“Mental Health and Lifestyle Habits (2019–2024)”</strong>, and it was created to explore the relationship between people’s lifestyle choices and their mental well-being. The data was collected from individuals around the world between 2019 and 2024 using online surveys and self-reported questionnaires.</p>
<p>The dataset was uploaded to Kaggle by <strong>Atharva Soundankar</strong> in 2025 and is publicly available for analysis. You can access it at the following link:<br>
<a href="https://www.kaggle.com/datasets/atharvasoundankar/mental-health-and-lifestyle-habits-2019-2024/data">Soundankar, Atharva. <em>Mental Health and Lifestyle Habits (2019–2024)</em>. Kaggle, 2025</a></p>
<p>This dataset includes 12 variables:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 6%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Country</code></td>
<td>chr</td>
<td>The respondent’s country of residence</td>
</tr>
<tr class="even">
<td><code>Age</code></td>
<td>dbl</td>
<td>Age of the respondent (in years)</td>
</tr>
<tr class="odd">
<td><code>Gender</code></td>
<td>chr</td>
<td>Gender identity of the respondent</td>
</tr>
<tr class="even">
<td><code>Exercise Level</code></td>
<td>chr</td>
<td>Frequency or intensity of physical activity (e.g., low, moderate, high)</td>
</tr>
<tr class="odd">
<td><code>Diet Type</code></td>
<td>chr</td>
<td>Type of diet (e.g., vegetarian, vegan, balanced, keto, junk food)</td>
</tr>
<tr class="even">
<td><code>Sleep Hours</code></td>
<td>dbl</td>
<td>Average number of hours of sleep per day</td>
</tr>
<tr class="odd">
<td><code>Stress Level</code></td>
<td>chr</td>
<td>Self-reported stress level (e.g., low, moderate, high)</td>
</tr>
<tr class="even">
<td><code>Mental Health Condition</code></td>
<td>chr</td>
<td>Any diagnosed mental health condition (e.g., anxiety, depression, PTSD)</td>
</tr>
<tr class="odd">
<td><code>Work Hours per Week</code></td>
<td>dbl</td>
<td>Number of hours worked per week</td>
</tr>
<tr class="even">
<td><code>Screen Time per Day (Hours)</code></td>
<td>dbl</td>
<td>Average number of hours spent looking at screens each day</td>
</tr>
<tr class="odd">
<td><code>Social Interaction Score</code></td>
<td>dbl</td>
<td>Self-rated score of social connection or engagement on scale (1–10)</td>
</tr>
<tr class="even">
<td><code>Happiness Score</code></td>
<td>dbl</td>
<td>Self-reported happiness score on scale (1–10)</td>
</tr>
</tbody>
</table>
<p>These variables provide a mix of <strong>demographic</strong>, <strong>behavioral</strong>, and <strong>psychological</strong> information that allows us to investigate how different aspects of daily life and mental health may influence a person’s overall happiness.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>Mental.Health.Lifestyle <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Mental_Health_Lifestyle_Dataset.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Mental.Health.Lifestyle)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 12
  Country   Age Gender `Exercise Level` `Diet Type` `Sleep Hours` `Stress Level`
  &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;            &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt;         
1 Brazil     48 Male   Low              Vegetarian            6.3 Low           
2 Austra…    31 Male   Moderate         Vegan                 4.9 Low           
3 Japan      37 Female Low              Vegetarian            7.2 High          
4 Brazil     35 Male   Low              Vegan                 7.2 Low           
5 Germany    46 Male   Low              Balanced              7.3 Low           
6 Japan      23 Other  Moderate         Balanced              2.7 Moderate      
# ℹ 5 more variables: `Mental Health Condition` &lt;chr&gt;,
#   `Work Hours per Week` &lt;dbl&gt;, `Screen Time per Day (Hours)` &lt;dbl&gt;,
#   `Social Interaction Score` &lt;dbl&gt;, `Happiness Score` &lt;dbl&gt;</code></pre>
</div>
</div>
<section id="data-limitations" class="level3">
<h3 class="anchored" data-anchor-id="data-limitations">Data Limitations</h3>
<p>Although the “Mental Health and Lifestyle Habits Dataset (2019–2024)” is useful for practicing data analysis and modeling, it has several problems that we should keep in mind:</p>
<p><strong>The data is self-reported:</strong></p>
<p>All the information in this dataset comes from people filling out surveys about themselves. This means there is no way to check if what they reported is accurate. People might overestimate healthy habits (like saying they exercise more than they do) or underestimate unhealthy ones (like not getting enough sleep). They might also give answers they think are more socially acceptable instead of being completely honest. This can make the data less reliable.</p>
<p><strong>Some variables are unclear or inconsistent:</strong></p>
<p>Some of the questions in the dataset are vague or not measured well. For example:</p>
<p>“Stress Level” is said to be on a 1–10 scale in the Kaggle dataset’s description, but the data uses categories like “Low,” “Moderate,” and “High,” which does not match.</p>
<p>“Exercise Level” is just labeled as “Low,” “Moderate,” or “High,” but it doesn’t tell us how often or how intensely people exercise.</p>
<p>The “Mental Health Condition” column includes things like depression and anxiety, but it doesn’t explain how severe they are or how they were diagnosed. These conditions are very complex, and simple labels might not show the full picture.</p>
<p><strong>Some data is missing or unclear:</strong></p>
<p>For example, the “Gender” column includes a large number of people marked as “Other,” but it’s not clear what that means—whether they’re non-binary, chose not to say, or something else. Without more detail, it is hard to use this information meaningfully.</p>
<p><strong>The results might not apply to everyone:</strong></p>
<p>The dataset was collected between 2019 and 2024, a period that included the COVID-19 pandemic, which had a major impact on people’s daily lives and mental health. Because of this, the results might not reflect what’s normal in other years. Also, we do not know where the participants are from or how they were selected, so the dataset might not represent people from different countries, cultures, or income levels. That means any patterns we find might not apply to everyone.</p>
<p>Because of these issues, we should treat this dataset more like a practice dataset—similar to examples used in class—rather than something that gives real-world, trustworthy results. It’s still helpful for learning how to explore data and build models, but the results should not be taken as scientifically accurate.</p>
</section>
</section>
<section id="data-wrangling-optional-section" class="level2">
<h2 class="anchored" data-anchor-id="data-wrangling-optional-section">Data Wrangling (Optional Section)</h2>
<p>The dataset I imported is already in a tidy format, meaning each row represents one observation and each column represents a variable. Therefore, no structural reshaping of the data was required.</p>
<p>However, to build and evaluate a predictive model effectively, it is essential to split the data into two parts: a <strong>training set</strong> and a <strong>test set</strong>. The training set (80% of the data) will be used to build the model and identify relationships between predictor variables—such as lifestyle habits and demographic characteristics—and the response variable, which is the <strong>Happiness Score</strong>. The test set (20% of the data) is held out and used to assess how well the model performs on new, unseen data.</p>
<p>This kind of split is important because it prevents overfitting and helps evaluate how well the model will generalize in real-world applications. The 80/20 ratio is a standard practice that strikes a balance between having enough data to train the model and reserving enough to test it meaningfully. To ensure reproducibility of the results, a random seed was set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a> n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(Mental.Health.Lifestyle)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a> train_indices <span class="ot">&lt;-</span> <span class="fu">sample</span>(n, <span class="at">size =</span> <span class="fu">floor</span>(<span class="fl">0.8</span><span class="sc">*</span>n))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a> MHL_train <span class="ot">&lt;-</span> Mental.Health.Lifestyle[train_indices,]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a> MHL_test <span class="ot">&lt;-</span> Mental.Health.Lifestyle[<span class="sc">-</span>train_indices,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="handling-missing-data" class="level3">
<h3 class="anchored" data-anchor-id="handling-missing-data">Handling Missing Data</h3>
<p>Before proceeding with modeling or analysis, it’s important to check for any missing data. Identifying missing values early allows us to decide whether to impute (fill in), remove, or otherwise handle them to avoid bias or errors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">miss_var_summary</span>(Mental.Health.Lifestyle)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
   variable                    n_miss pct_miss
   &lt;chr&gt;                        &lt;int&gt;    &lt;num&gt;
 1 Country                          0        0
 2 Age                              0        0
 3 Gender                           0        0
 4 Exercise Level                   0        0
 5 Diet Type                        0        0
 6 Sleep Hours                      0        0
 7 Stress Level                     0        0
 8 Mental Health Condition          0        0
 9 Work Hours per Week              0        0
10 Screen Time per Day (Hours)      0        0
11 Social Interaction Score         0        0
12 Happiness Score                  0        0</code></pre>
</div>
</div>
<p>After running the code, there are no missing values in any of the columns. This simplifies the data preparation process, as no imputation or data cleaning for missing values is currently required.</p>
</section>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<p>My objective is to understand how lifestyle factors may influence an individual’s overall happiness, specifically focusing on how <strong>screen time</strong> and <strong>sleep hours</strong> might relate to the <strong>happiness score</strong>. Since I have not yet conducted feature selection (e.g., via LASSO), I do not know which predictors are statistically most important. However, based on intuition and prior research, I initially suspect that <strong>screen time per day</strong> and <strong>sleep hours</strong> could play a meaningful role in predicting happiness.</p>
<p>This section explores three key variables:</p>
<ul>
<li><p><code>Happiness Score</code> (the response variable)</p></li>
<li><p><code>Screen Time per Day (Hours)</code> (a potentially important predictor)</p></li>
<li><p><code>Sleep Hours</code> (a potentially important predictor)</p></li>
</ul>
<p>The following analysis examines the distributions of these variables, checks for unusual or problematic values, and begins to explore their relationships to guide future modeling.</p>
<section id="happiness-score-response-variable" class="level3">
<h3 class="anchored" data-anchor-id="happiness-score-response-variable">1. Happiness Score (Response Variable)</h3>
<p><strong>Check for unusual values</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># since `Happiness Score` is on the scale 1 - 10</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>unusual_happiness <span class="ot">&lt;-</span> MHL_train <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">1</span> <span class="sc">|</span> <span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">10</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>unusual_happiness</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 12
# ℹ 12 variables: Country &lt;chr&gt;, Age &lt;dbl&gt;, Gender &lt;chr&gt;, Exercise Level &lt;chr&gt;,
#   Diet Type &lt;chr&gt;, Sleep Hours &lt;dbl&gt;, Stress Level &lt;chr&gt;,
#   Mental Health Condition &lt;chr&gt;, Work Hours per Week &lt;dbl&gt;,
#   Screen Time per Day (Hours) &lt;dbl&gt;, Social Interaction Score &lt;dbl&gt;,
#   Happiness Score &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Then, there is no unusual values — all scores fall between 1 and 10, as expected.</p>
<p><strong>Summary statistics</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>MHL_train <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_total =</span> <span class="fu">n</span>(), </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_missing =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(<span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span>)), </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(<span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(<span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span>, <span class="fl">0.25</span>),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(<span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span>),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(<span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span>, <span class="fl">0.75</span>),</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(<span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span>),</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span>),</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(<span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span>),</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(<span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 10
  num_total num_missing   min    Q1 median    Q3   max  mean    sd   IQR
      &lt;int&gt;       &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1      2400           0     1   3.2    5.4   7.5    10  5.40  2.55   4.3</code></pre>
</div>
</div>
<p><strong>Visualization</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> MHL_train, </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">x =</span> <span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>          )</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>        ) <span class="sc">+</span> </span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_histogram</span>(<span class="at">center =</span> <span class="dv">5</span>, <span class="at">binwidth =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram of Happiness Score"</span>, <span class="at">x =</span> <span class="st">"Happiness Score"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Math437_Project_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<p>The happiness scores range from 1 to 10, with an average (mean) of approximately 5.4 and a standard deviation of about 2.55. The distribution appears fairly spread out and roughly uniform across the scale, meaning that respondents reported happiness levels that are quite evenly distributed from low to high. This uniformity is somewhat unusual for a subjective well-being measure, which often shows skewed or clustered patterns in real-world data. The absence of extreme outliers is also notable. Overall, this pattern raises questions about how the happiness scores were generated or categorized—whether the respondents truly felt evenly distributed levels of happiness, or if the data collection process or scale used may have led to artificial uniformity.</p>
</section>
<section id="screen-time-per-day-hours" class="level3">
<h3 class="anchored" data-anchor-id="screen-time-per-day-hours">2. Screen Time per Day (Hours)</h3>
<p><strong>Check for unusual values</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># since one day has 24 hours and the number of hours cannot be negative </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>unusual_screen_time <span class="ot">&lt;-</span> MHL_train <span class="sc">|&gt;</span> <span class="fu">filter</span>(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Screen Time per Day (Hours)</span><span class="st">`</span><span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">|</span> <span class="st">`</span><span class="at">Screen Time per Day (Hours)</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">24</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>unusual_screen_time</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 12
# ℹ 12 variables: Country &lt;chr&gt;, Age &lt;dbl&gt;, Gender &lt;chr&gt;, Exercise Level &lt;chr&gt;,
#   Diet Type &lt;chr&gt;, Sleep Hours &lt;dbl&gt;, Stress Level &lt;chr&gt;,
#   Mental Health Condition &lt;chr&gt;, Work Hours per Week &lt;dbl&gt;,
#   Screen Time per Day (Hours) &lt;dbl&gt;, Social Interaction Score &lt;dbl&gt;,
#   Happiness Score &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Then, there is no extreme values — all screen times fall between 0 and 24.</p>
<p><strong>Summary statistics</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>MHL_train <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_total =</span> <span class="fu">n</span>(),</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_missing =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(<span class="st">`</span><span class="at">Screen Time per Day (Hours)</span><span class="st">`</span>)),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(<span class="st">`</span><span class="at">Screen Time per Day (Hours)</span><span class="st">`</span>),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(<span class="st">`</span><span class="at">Screen Time per Day (Hours)</span><span class="st">`</span>, <span class="fl">0.25</span>),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(<span class="st">`</span><span class="at">Screen Time per Day (Hours)</span><span class="st">`</span>),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(<span class="st">`</span><span class="at">Screen Time per Day (Hours)</span><span class="st">`</span>, <span class="fl">0.75</span>),</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(<span class="st">`</span><span class="at">Screen Time per Day (Hours)</span><span class="st">`</span>),</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Screen Time per Day (Hours)</span><span class="st">`</span>),</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(<span class="st">`</span><span class="at">Screen Time per Day (Hours)</span><span class="st">`</span>),</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(<span class="st">`</span><span class="at">Screen Time per Day (Hours)</span><span class="st">`</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 10
  num_total num_missing   min    Q1 median    Q3   max  mean    sd   IQR
      &lt;int&gt;       &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1      2400           0     2   3.5    5.1   6.6     8  5.08  1.75   3.1</code></pre>
</div>
</div>
<p><strong>Visualization</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> MHL_train, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">x =</span> <span class="st">`</span><span class="at">Screen Time per Day (Hours)</span><span class="st">`</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>          )</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>        ) <span class="sc">+</span> </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_histogram</span>(<span class="at">center =</span> <span class="dv">5</span>, <span class="at">binwidth =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram of Screen Time per Day"</span>, <span class="at">x =</span> <span class="st">"Screen Time per Day (Hours)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Math437_Project_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> Screen time per day ranges from 2 to 8 hours, with an average of around 5.08 hours. The data seems evenly spread out across this range, with no extreme values. However, this even distribution is unusual and may suggest that the data was collected in a way that limited the variety of screen time reported. For example, the data might have been grouped into specific time ranges (like 2 to 3 hours, 4 to 5 hours, etc.), which could explain why there are no values below 2 hours or above 8 hours. Normally, we’d expect more variation in screen time, so this pattern might point to how the data was recorded or categorized.</p>
</section>
<section id="sleep-hours" class="level3">
<h3 class="anchored" data-anchor-id="sleep-hours">3. Sleep Hours</h3>
<p><strong>Check for unusual values</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># since one day has 24 hours and the number of hours cannot be negative </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>unusual_sleep <span class="ot">&lt;-</span> MHL_train <span class="sc">|&gt;</span> <span class="fu">filter</span>(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Sleep Hours</span><span class="st">`</span><span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">|</span> <span class="st">`</span><span class="at">Sleep Hours</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">24</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>unusual_sleep</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 12
# ℹ 12 variables: Country &lt;chr&gt;, Age &lt;dbl&gt;, Gender &lt;chr&gt;, Exercise Level &lt;chr&gt;,
#   Diet Type &lt;chr&gt;, Sleep Hours &lt;dbl&gt;, Stress Level &lt;chr&gt;,
#   Mental Health Condition &lt;chr&gt;, Work Hours per Week &lt;dbl&gt;,
#   Screen Time per Day (Hours) &lt;dbl&gt;, Social Interaction Score &lt;dbl&gt;,
#   Happiness Score &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Then, there is no invalid sleep durations — all values fall within a realistic 0–24 hour range.</p>
<p><strong>Summary statistics</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>MHL_train <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_total =</span> <span class="fu">n</span>(),</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_missing =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(<span class="st">`</span><span class="at">Sleep Hours</span><span class="st">`</span>)),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(<span class="st">`</span><span class="at">Sleep Hours</span><span class="st">`</span>),</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(<span class="st">`</span><span class="at">Sleep Hours</span><span class="st">`</span>, <span class="fl">0.25</span>),</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(<span class="st">`</span><span class="at">Sleep Hours</span><span class="st">`</span>),</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(<span class="st">`</span><span class="at">Sleep Hours</span><span class="st">`</span>, <span class="fl">0.75</span>),</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(<span class="st">`</span><span class="at">Sleep Hours</span><span class="st">`</span>),</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Sleep Hours</span><span class="st">`</span>),</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(<span class="st">`</span><span class="at">Sleep Hours</span><span class="st">`</span>),</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(<span class="st">`</span><span class="at">Sleep Hours</span><span class="st">`</span>)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 10
  num_total num_missing   min    Q1 median    Q3   max  mean    sd   IQR
      &lt;int&gt;       &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1      2400           0   1.4   5.5    6.5   7.5  11.3  6.49  1.49     2</code></pre>
</div>
</div>
<p><strong>Visualization</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> MHL_train, </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">x =</span> <span class="st">`</span><span class="at">Sleep Hours</span><span class="st">`</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>          )</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>        ) <span class="sc">+</span> </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_histogram</span>(<span class="at">center =</span> <span class="dv">6</span>, <span class="at">binwidth =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram of Sleep Hours"</span>, <span class="at">x =</span> <span class="st">"Sleep Hours"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Math437_Project_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> Sleep hours range from about 1.4 to 11.3 hours, with an average of approximately 6.5 hours. Most people sleep between 5.5 and 7.5 hours, which centers around the recommended 7–8 hours of sleep per night. The distribution has a bell-shaped curve, which is typical for sleep data. There are no extreme outliers, and the spread seems reasonable. This suggests that the sleep data is likely realistic and reflects a natural variation in how long people sleep.</p>
</section>
<section id="relationship-between-lifestyle-and-happiness" class="level3">
<h3 class="anchored" data-anchor-id="relationship-between-lifestyle-and-happiness">4. Relationship between Lifestyle and Happiness</h3>
<p><strong>a) Screen Time vs Happiness</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> MHL_train,</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">`</span><span class="at">Screen Time per Day (Hours)</span><span class="st">`</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>         )</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>       ) <span class="sc">+</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Screen Time per Day (Hours) vs. Happiness Score"</span>,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="at">x =</span> <span class="st">"Screen Time per Day (Hours)"</span>,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="at">y =</span> <span class="st">"Happiness Score"</span>) <span class="sc">+</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Math437_Project_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Scatterplot Interpretation:</strong></p>
<p>The scatterplot shows that happiness scores are fairly spread out across all levels of screen time. There is no clear upward or downward trend, although the smoothed line suggests a slight dip in happiness at moderate screen time levels, followed by a small increase. Overall, no strong pattern emerges.</p>
<p><strong>Correlation Analysis:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(MHL_train<span class="sc">$</span><span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span>, MHL_train<span class="sc">$</span><span class="st">`</span><span class="at">Screen Time per Day (Hours)</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04427989</code></pre>
</div>
</div>
<p>The correlation coefficient is approximately <strong>0.044</strong>, indicating a <strong>very weak positive linear relationship</strong> between screen time and happiness. This supports the visual observation that screen time, at least on its own, does not have a meaningful impact on happiness in this dataset.</p>
<p><strong>Conclusion:</strong></p>
<p>There appears to be <strong>no significant relationship</strong> between screen time and happiness score. People with both low and high screen time report a wide range of happiness scores, and the slight trends in the data are not strong enough to suggest a real pattern. That means, screen time might still play a role when combined with other factors like sleep or stress. To get a better understanding of what influences happiness, it will be helpful to look at other lifestyle habits such as Sleep Hours.</p>
<p><strong>b) Sleep Hours vs Happiness</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> MHL_train,</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">`</span><span class="at">Sleep Hours</span><span class="st">`</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>         )</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>       ) <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sleep Hours vs. Happiness Score"</span>,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="at">x =</span> <span class="st">"Sleep Hours"</span>,</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="at">y =</span> <span class="st">"Happiness Score"</span>) <span class="sc">+</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Math437_Project_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Scatterplot Interpretation:</strong></p>
<p>The scatterplot shows the relationship between sleep hours and happiness score. Although the data points are highly dispersed, a smoothed trend line reveals a subtle non-linear pattern. Specifically, individuals who report very few hours of sleep (e.g., less than 4 hours) tend to have slightly higher happiness scores, but the trend then dips and gradually levels off as sleep duration increases. Overall, the association between sleep and happiness appears weak and inconsistent, suggesting that sleep duration alone does not strongly predict happiness.</p>
<p><strong>Correlation Analysis:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(MHL_train<span class="sc">$</span><span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span>, MHL_train<span class="sc">$</span><span class="st">`</span><span class="at">Sleep Hours</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.00852507</code></pre>
</div>
</div>
<p>The correlation coefficient is <strong>0.0085</strong>, which is extremely close to zero. This confirms that there’s essentially <strong>no linear relationship</strong> between sleep and happiness in this dataset.</p>
<p><strong>Conclusion:</strong></p>
<p>The effect of sleep hours on happiness score is very small. This suggests that <strong>sleep alone likely does not play a major role</strong> in determining happiness — though it could interact with other factors like stress, screen time, or social interaction.</p>
<p>The exploratory analysis suggests that neither <strong>screen time</strong> nor <strong>sleep hours</strong> individually show a strong relationship with <strong>happiness score</strong>. To better understand what drives happiness, we now turn to <strong>modeling</strong>, where we will consider <strong>multiple lifestyle variables</strong> together. By using statistical and machine learning techniques, such as <strong>LASSO regression</strong>, we can identify which predictors are most influential and how they interact to impact happiness.</p>
</section>
</section>
<section id="modeling" class="level2">
<h2 class="anchored" data-anchor-id="modeling">Modeling</h2>
<p>I used <strong>LASSO regression (Least Absolute Shrinkage and Selection Operator)</strong> to model the relationship between lifestyle factors and happiness score. LASSO is particularly useful when we have many predictors, some of which may be irrelevant. It performs both:</p>
<ul>
<li><p><strong>Regularization</strong>, to avoid overfitting by penalizing large coefficients</p></li>
<li><p><strong>Variable selection</strong>, by shrinking some coefficients to exactly zero</p></li>
</ul>
<p>This makes the resulting model more interpretable and potentially more generalizable to new data.</p>
<p><strong>Model Specification and Preprocessing</strong></p>
<p>I defined a LASSO regression model with a tunable penalty:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>lasso_model <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>(<span class="at">mode =</span> <span class="st">"regression"</span>,</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="at">engine =</span> <span class="st">"glmnet"</span>,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="at">penalty =</span> <span class="fu">tune</span>(),</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="at">mixture =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, I created a preprocessing recipe and combined the model and recipe into a workflow:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>lasso_recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span> <span class="sc">~</span> .,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> MHL_train</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>()) <span class="sc">|&gt;</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_numeric_predictors</span>())</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>lasso_wflow <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(lasso_model) <span class="sc">|&gt;</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(lasso_recipe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Cross-Validation and Tuning</strong></p>
<p>I used 10-fold cross-validation to tune the penalty parameter and tuned the penalty parameter over 200 values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>MHL_folds<span class="ot">&lt;-</span><span class="fu">vfold_cv</span>(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  MHL_train,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">v=</span><span class="dv">10</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>lasso_grid<span class="ot">&lt;-</span><span class="fu">grid_regular</span>(<span class="fu">penalty</span>(), <span class="at">levels =</span> <span class="dv">200</span>)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>lasso_tune<span class="ot">&lt;-</span><span class="fu">tune_grid</span>(lasso_model,</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>                      lasso_recipe,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>                      <span class="at">resamples=</span> MHL_folds,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>                      <span class="at">grid=</span> lasso_grid,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>                      <span class="at">metrics=</span> <span class="fu">metric_set</span>(rmse))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I visualized the tuning results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>lasso_tune<span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>() <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.metric<span class="sc">==</span> <span class="st">"rmse"</span>)<span class="sc">|&gt;</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span> penalty,<span class="at">y=</span>mean)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x=</span> penalty,<span class="at">xend=</span> penalty, <span class="at">y=</span> mean<span class="sc">+</span> std_err,<span class="at">yend=</span> mean<span class="sc">-</span>std_err)) <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_x_log10</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Math437_Project_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Best Model Selection and Fitting</strong></p>
<p>I selected the penalty with the lowest RMSE (Root Mean Squared Error):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>lasso_min <span class="ot">&lt;-</span> lasso_tune <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_best</span>(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">metric =</span> <span class="st">"rmse"</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>lasso_min</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  penalty .config               
    &lt;dbl&gt; &lt;chr&gt;                 
1  0.0554 Preprocessor1_Model175</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>lasso_wflow_final <span class="ot">&lt;-</span> lasso_wflow <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalize_workflow</span>(<span class="at">parameters =</span> lasso_min)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>lasso_fit <span class="ot">&lt;-</span> <span class="fu">fit</span>(lasso_wflow_final,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> MHL_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Prediction and Model Performance</strong></p>
<p>I chose <strong>Root Mean Squared Error (RMSE)</strong> as the performance metric because it provides a clear measure of how well the model predicts the <code>Happiness Score</code>, with errors expressed in the same units. RMSE calculates the square root of the average squared differences between predicted and actual values, which penalizes larger errors more heavily. This makes it a useful and interpretable way to evaluate the accuracy of a regression model, especially when predicting a continuous outcome like <code>Happiness Score</code>.</p>
<p>I evaluated the model on the test set:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>lasso_predict <span class="ot">&lt;-</span> <span class="fu">augment</span>(lasso_fit,</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">new_data =</span> MHL_test</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                         )</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>lasso_predict <span class="sc">|&gt;</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rmse</span>(</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">truth =</span> <span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span>,</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">estimate =</span> .pred</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard        2.60</code></pre>
</div>
</div>
<p>The RMSE on the test set was <strong>2.598</strong>, which means the model’s predictions are off by about 2.6 points on average. Given that the <code>Happiness Score</code> ranges from 0 to 10, this level of error suggests <strong>moderate predictive accuracy</strong>—the model captures some meaningful patterns in the data but still leaves a substantial portion of the variation unexplained. This indicates that while the model is somewhat useful, there may be other important factors influencing happiness that are not captured by the predictors included.</p>
<p><strong>Coefficients and Significance</strong></p>
<p>I extracted the model coefficients:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>lasso_coef <span class="ot">&lt;-</span> lasso_fit <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>lasso_coef <span class="sc">|&gt;</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(estimate)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 26 × 3
   term                         estimate penalty
   &lt;chr&gt;                           &lt;dbl&gt;   &lt;dbl&gt;
 1 (Intercept)                  5.40      0.0554
 2 Diet Type_Vegetarian         0.0621    0.0554
 3 Social Interaction Score    -0.0606    0.0554
 4 Screen Time per Day (Hours)  0.0573    0.0554
 5 Exercise Level_Low          -0.0567    0.0554
 6 Country_Japan               -0.0259    0.0554
 7 Country_Canada               0.00118   0.0554
 8 Gender_Male                  0.000262  0.0554
 9 Age                          0         0.0554
10 Sleep Hours                  0         0.0554
# ℹ 16 more rows</code></pre>
</div>
</div>
<p>LASSO selected 8 variables with non-zero coefficients (included the intercept). To assess statistical significance, I used a standard linear model and checked 95% confidence intervals:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>lm_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">Happiness Score</span><span class="st">`</span> <span class="sc">~</span> </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>               <span class="st">`</span><span class="at">Diet Type</span><span class="st">`</span> <span class="sc">+</span> </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>               <span class="st">`</span><span class="at">Social Interaction Score</span><span class="st">`</span> <span class="sc">+</span> </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>               <span class="st">`</span><span class="at">Screen Time per Day (Hours)</span><span class="st">`</span> <span class="sc">+</span> </span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>               <span class="st">`</span><span class="at">Exercise Level</span><span class="st">`</span> <span class="sc">+</span> </span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>               <span class="st">`</span><span class="at">Country</span><span class="st">`</span> <span class="sc">+</span> </span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>               <span class="st">`</span><span class="at">Gender</span><span class="st">`</span>,</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> MHL_train)  </span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>conf_intervals <span class="ot">&lt;-</span> <span class="fu">confint</span>(lm_model, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>conf_intervals</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                     2.5 %       97.5 %
(Intercept)                    4.997113620  6.070873945
`Diet Type`Junk Food          -0.221973229  0.406008192
`Diet Type`Keto               -0.367307125  0.276860576
`Diet Type`Vegan              -0.350542466  0.294138683
`Diet Type`Vegetarian         -0.027753982  0.615275392
`Social Interaction Score`    -0.086451628 -0.006668924
`Screen Time per Day (Hours)`  0.006735754  0.123273911
`Exercise Level`Low           -0.578269429 -0.078115894
`Exercise Level`Moderate      -0.439291666  0.065648209
CountryBrazil                 -0.588142151  0.192580062
CountryCanada                 -0.400780960  0.360805223
CountryGermany                -0.548976039  0.237555982
CountryIndia                  -0.616148910  0.158268547
CountryJapan                  -0.737865428  0.036165263
CountryUSA                    -0.596192652  0.166992208
GenderMale                    -0.100042675  0.399369053
GenderOther                   -0.181244954  0.315859637</code></pre>
</div>
</div>
<p>Only 3 predictors had confidence intervals that did not include 0, suggesting stronger evidence of an association:</p>
<ul>
<li><p>Social Interaction Score</p></li>
<li><p>Screen Time per Day (Hours)</p></li>
<li><p><code>Exercise Level</code>Low</p></li>
</ul>
<p>However, their confidence intervals were <strong>very close to 0</strong>, which means that while these predictors are statistically significant, the <strong>magnitude of their effects is small</strong>. This implies that the relationship with happiness is likely weak in practical terms, even if statistically detectable. (To illustrate, in the “Exploratory Data Analysis” section, we saw that the relationship between <code>Screen Time per Day (Hours)</code> and <code>Happiness Score</code> was very weak.)</p>
<p><strong>Summary</strong></p>
<p>LASSO regression allowed me to build a predictive and interpretable model by selecting a subset of relevant predictors. While the overall model has moderate predictive performance, it highlighted a few key lifestyle factors—like social interaction, screen time, and exercise—that are more consistently related to happiness. However, while three predictors had confidence intervals that excluded zero, their effect sizes were small and close to zero, suggesting that the relationships — though statistically significant — may not be practically strong.</p>
</section>
<section id="insights" class="level2">
<h2 class="anchored" data-anchor-id="insights">Insights</h2>
<p>To summarize the key findings of the model, I generated a plot of the statistically significant predictors of happiness based on a standard linear regression model. The graph below displays each predictor whose 95% confidence interval does not include zero, meaning we have stronger statistical evidence that they are associated with happiness.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>coef_df <span class="ot">&lt;-</span> <span class="fu">tidy</span>(lm_model, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>significant_coefs <span class="ot">&lt;-</span> coef_df <span class="sc">|&gt;</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">!=</span> <span class="st">"(Intercept)"</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>         conf.low <span class="sc">*</span> conf.high <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(significant_coefs, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(term, estimate), <span class="at">y =</span> estimate)) <span class="sc">+</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> conf.low, <span class="at">ymax =</span> conf.high), <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Statistically Significant Predictors of Happiness"</span>,</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Predictor"</span>,</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Estimated Coefficient"</span></span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Math437_Project_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From this plot, we see that three predictors—Social Interaction Score, Screen Time per Day (Hours), and Exercise Level (Low)—had confidence intervals that did not include zero, indicating statistically significant associations with happiness. However, their estimated effects are close to zero, suggesting that these relationships are weak in practical terms. This finding is consistent with results from the exploratory data analysis, particularly the weak association observed between screen time and happiness. Overall, while the model identifies some lifestyle factors related to happiness, the effect sizes are small, and predictive accuracy remains moderate. The figure reinforces the conclusion that although lifestyle habits like social engagement, screen use, and physical activity are statistically linked to happiness, none of them individually exerts a strong influence. This suggests that happiness is likely shaped by a more complex combination of factors.</p>
<section id="limitations-and-future-work" class="level3">
<h3 class="anchored" data-anchor-id="limitations-and-future-work">Limitations and Future Work</h3>
<p><strong>Limitations</strong></p>
<p>While the LASSO model helped identify a small subset of predictors and provided a reasonably interpretable model, there are several limitations:</p>
<p><strong>- Prediction Accuracy:</strong> The RMSE of 2.598 indicates that the model’s predictions deviate from actual happiness scores by an average of about 2.6 points on a 0–10 scale. This suggests moderate predictive performance, but also room for improvement—particularly for individuals at the extremes of the happiness scale (very low or very high scores).</p>
<p><strong>- Weak Predictive Relationships:</strong> Although three predictors—<strong>social interaction</strong>, <strong>screen time</strong>, and <strong>exercise</strong>—were statistically significant, their coefficients were very close to zero. This implies that their real-world impact on happiness may be quite limited. The model may be missing other unmeasured variables that more strongly influence happiness.</p>
<p><strong>- Assumptions of Linear Modeling:</strong> Linear regression assumes a linear relationship between predictors and the outcome, homoscedasticity, and independence of errors. In reality, relationships between lifestyle factors and happiness may be non-linear or influenced by interactions that this model does not capture.</p>
<p><strong>- Multicollinearity:</strong> Some predictors in the model, such as exercise, diet, and screen time, may be correlated with each other. This multicollinearity can inflate the standard errors of coefficients in the linear model, making it harder to determine which variables truly influence happiness. While LASSO helps mitigate this issue by shrinking and selecting coefficients, it may still obscure the interpretation of individual effects in the presence of strongly correlated predictors.</p>
<p><strong>- Lack of Temporal or Causal Information:</strong> The dataset is observational and cross-sectional, meaning we cannot infer causality. For example, while people who exercise more report higher happiness, we cannot tell if exercise causes happiness or if happier people are more likely to exercise.</p>
<p><strong>- Potential Biases in Data Collection:</strong> The dataset may not be fully representative across cultures, age groups, or socioeconomic backgrounds. Some variables (e.g., happiness, social interaction) are self-reported, which introduces measurement error and possible social desirability bias.</p>
<p><strong>Future Work</strong></p>
<p>To address these limitations, several paths for future research are recommended:</p>
<p><strong>- Collect Longitudinal Data:</strong> Tracking individuals over time would allow us to better understand causal relationships and how changes in lifestyle affect happiness.</p>
<p><strong>- Explore Non-Linear Models:</strong> Using tree-based models (e.g., Random Forest or XGBoost) could help uncover complex, non-linear interactions between variables that linear models cannot capture.</p>
<p><strong>- Investigate Multicollinearity and Dimensionality Reduction:</strong> Future work could further investigate correlations among predictors and consider techniques like Principal Component Analysis (PCA) or more robust regularization methods to reduce multicollinearity. These approaches may help clarify underlying patterns and improve model stability and interpretability.</p>
<p><strong>- Feature Engineering:</strong> Creating new variables that better capture lifestyle habits (e.g., a composite wellness index or interaction terms) could improve predictive power.</p>
<p><strong>- Expand Data Collection:</strong> Including variables like mental health status, sleep quality, financial stress, and life events might help capture other key drivers of happiness.</p>
<p><strong>- Ethical Considerations:</strong> It is important to avoid over-interpreting or misusing the results. For example, suggesting policy based on weak or non-causal associations could be misleading. Also, any recommendations should be sensitive to cultural and individual differences in how happiness is experienced and reported.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>